version: 0.2
            
phases:
  install:
    commands:
    - aws cloudformation package --template-file template.yaml --s3-bucket democloudlambda --output-template-file outputemplatefile.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputemplatefile.yaml
  name: myApplp
